// ── Core types ──
export {
	type TargetId,
	type SessionId,
	type ElementRef,
	type TabId,
	targetId,
	sessionId,
	elementIndex,
	tabId,
	type Result,
	ok,
	err,
	type Position,
	type Rect,
	LogLevel,
	type DeepPartial,
	type Awaitable,
} from './types.js';

// ── Errors ──
export {
	OpenBrowserError,
	ViewportError,
	LaunchFailedError,
	NavigationFailedError,
	ViewportCrashedError,
	ContextualViewportError,
	AgentError,
	AgentStalledError,
	StepLimitExceededError,
	UrlBlockedError,
	PageExtractionError,
	ModelError,
	ModelThrottledError,
	CommandFailedError,
	ProviderError,
	SchemaViolationError,
} from './errors.js';

// ── Logging ──
export {
	Logger,
	createLogger,
	setGlobalLogLevel,
	getGlobalLogLevel,
	setLogColors,
	setLogTimestamps,
} from './logging.js';

// ── Observability ──
export {
	timed,
	withTiming,
	Stopwatch,
	type TimingResult,
} from './telemetry.js';

// ── Utils ──
export { generateId, matchesUrlPattern, isUrlPermitted, sleep, withDeadline, Timer } from './utils.js';

// ── Config ──
export { Config } from './config/index.js';
export type { ViewportConfig, AgentConfig as AgentConfigSchema, GlobalConfig } from './config/index.js';

// ── LLM ──
export {
	type LanguageModel,
	type InferenceOptions,
	type ModelProvider,
	type InferenceResult,
	type InferenceUsage,
	type Message,
	type SystemMessage,
	type UserMessage,
	type AssistantMessage,
	type ToolResultMessage,
	type ToolCall,
	type ContentPart,
	type TextContent,
	type ImageContent,
	systemMessage,
	userMessage,
	assistantMessage,
	toolResultMessage,
	textContent,
	imageContent,
	VercelModelAdapter,
	type VercelModelAdapterOptions,
	zodToJsonSchema,
	optimizeSchemaForModel,
	optimizeJsonSchemaForModel,
	type SchemaOptimizationOptions,
} from './model/index.js';

// ── Browser ──
export {
	Viewport,
	type ViewportOptions,
	LaunchProfile,
	EventHub,
	BaseGuard,
	type GuardContext,
	VisualTracer,
	type VisualTracerOptions,
	type TabDescriptor,
	type ViewportSnapshot,
	type ViewportHistory,
	type LaunchOptions,
	type PageState,
	type ViewportEventMap,
	type ViewportRequestMap,
	type NavigateEvent,
	type ClickEvent,
	type InputEvent,
	type ScrollEvent,
	type ScreenshotEvent,
	type ScreenshotResult,
	type DownloadEvent,
	type PopupEvent,
	type SecurityEvent,
	type CrashEvent,
} from './viewport/index.js';

// ── DOM ──
export {
	PageAnalyzer,
	type PageAnalyzerOptions,
	SnapshotBuilder,
	TreeRenderer,
	type RendererOptions,
	extractMarkdown,
	htmlToMarkdown,
	extractTextContent,
	extractLinks,
	chunkText,
	type MarkdownExtractionOptions,
	type PageTreeNode,
	type SelectorIndex,
	type RenderedPageState,
	type DOMRect,
	type CDPSnapshotResult,
	type AXNode,
	type TargetInfo,
	type TargetAllTrees,
	type InteractedElement,
	type MatchLevel,
	type SimplifiedNode,
} from './page/index.js';

// ── FileAccess ──
export {
	FileAccess,
	type FileAccessOptions,
	type FileInfo,
	type FileAccessState,
} from './sandbox/index.js';

// ── Commands ──
export {
	CommandExecutor,
	type CommandExecutorOptions,
	classifyViewportError,
	CommandCatalog,
	ContentExtractor,
	type CatalogEntry,
	type CatalogOptions,
	CommandSchema,
	type Command,
	type CommandName,
	type CommandResult,
	type ExecutionContext,
	type CustomCommandSpec,
	type ViewportErrorCategory,
	type InterpretedViewportError,
	TapCommandSchema,
	TypeTextCommandSchema,
	NavigateCommandSchema,
	BackCommandSchema,
	ScrollCommandSchema,
	PressKeysCommandSchema,
	ExtractCommandSchema,
	FinishCommandSchema,
	FocusTabCommandSchema,
	NewTabCommandSchema,
	CloseTabCommandSchema,
	WebSearchCommandSchema,
	UploadCommandSchema,
	SelectCommandSchema,
	CaptureCommandSchema,
	ReadPageCommandSchema,
	WaitCommandSchema,
	ScrollToCommandSchema,
	FindCommandSchema,
	SearchCommandSchema,
	ListOptionsCommandSchema,
	PickOptionCommandSchema,
	ExtractStructuredCommandSchema,
} from './commands/index.js';

// ── Agent ──
export {
	Agent,
	type AgentOptions,
	InstructionBuilder,
	StepPromptBuilder,
	buildCommandDescriptions,
	buildContextualCommands,
	buildExtractionInstructionBuilder,
	buildExtractionUserPrompt,
	clearTemplateCache,
	type PromptTemplate,
	type InstructionBuilderOptions,
	type StepInfo,
	type StepPromptBuilderOptions,
	ConversationManager,
	StallDetector,
	hashPageTree,
	hashTextContent,
	type PageSignature,
	type StallDetectorConfig,
	type StallCheckResult,
	ResultEvaluator,
	constructEvaluatorMessages,
	constructQuickCheckMessages,
	ReplayRecorder,
	type ReplayRecorderOptions,
	type AgentConfig,
	type AgentState,
	type AgentDecision,
	type AgentDecisionCompact,
	type AgentDecisionDirect,
	type StepRecord,
	ExecutionLog,
	type RunOutcome,
	type Reasoning,
	type PlanStep,
	type EvaluationResult,
	type QuickCheckResult,
	type CompactionPolicy,
	type StepTelemetry,
	type ExtractedVariable,
	type AccumulatedCost,
	type StepCostBreakdown,
	type PricingTable as AgentPricingTable,
	type PlanRevision,
	AgentDecisionSchema,
	AgentDecisionCompactSchema,
	AgentDecisionDirectSchema,
	ReasoningSchema,
	EvaluationResultSchema,
	QuickCheckResultSchema,
	PlanStepSchema,
	StrategyPlanSchema,
	PlanRevisionSchema,
	PRICING_TABLE,
	calculateStepCost,
	supportsDeepReasoning,
	supportsCoordinateMode,
	isCompactModel,
	DEFAULT_AGENT_CONFIG,
	type ConversationManagerOptions,
	type TrackedMessage,
	type ConversationManagerState,
	type ConversationEntry,
	type SerializedTrackedMessage,
	type MessageCategory,
	estimateTokens,
	estimateMessageTokens,
	redactSensitiveValues,
	redactMessage,
	redactMessages,
	extractTextContent as extractMessageTextContent,
	truncate,
} from './agent/index.js';

// ── Bridge ──
export { BridgeServer, type BridgeServerOptions, BridgeClient, type BridgeClientOptions, BridgeAdapter } from './bridge/index.js';

// ── Metering ──
export {
	UsageMeter,
	CompositeUsageMeter,
	BudgetDepletedError,
	estimateTokenCount,
	DEFAULT_COST_RATES,
	type UsageRecord,
	type CostRates,
	type PricingTable,
	type ModelRole,
	type ActionUsageRecord,
	type MeteringSummary,
	type ModelUsageBreakdown,
	type RoleUsageBreakdown,
	type BudgetPolicy,
	type BudgetState,
} from './metering/index.js';
